DROP DATABASE IF EXISTS emp_db;
CREATE DATABASE emp_db;

USE emp_db;

CREATE TABLE DEPARTMENT (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    depName VARCHAR(30) NOT NULL
);

CREATE TABLE empRole (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(30) NOT NULL,
    salary DECIMAL NOT NULL,
    DEPARTMENT_id INT,
    FOREIGN KEY (DEPARTMENT_id)
    REFERENCES DEPARTMENT(id)
    ON DELETE SET NULL
);

CREATE TABLE EMPLOYEE (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    empRole_id INT,
    manager_id INT REFERENCES employee(id),
    FOREIGN KEY (empRole_id)
    REFERENCES empRole(id)
    ON DELETE SET NULL
);
